services:
  rabbitmq:
    image: rabbitmq:4.3.0-rc.0-management-alpine
    hostname: rabbitmq
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "wohus"
      RABBITMQ_DEFAULT_PASS: "pass"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
